# ══════════════════════════════════════════════════════════════
# 3_supplementary_analyses.py
# Reproduces and verifies every estimate reported in the BMC Public
# Health manuscript that is NOT generated by 2_analysis.ipynb:
#   Table S4  — multiplicative interaction CI, RERI (delta + bootstrap)
#   Table S5  — wave-stratified autonomy PRs + exposure×wave tests
#   Table S6  — support-omitted model + multiple imputation (m=10)
#   Robustness — total vs direct effect, age-stratified PRs,
#                cluster-by-wave variance, E-value
#   Descriptives — Table 1 counts, weighted trend endpoints
# Every value is compared against the manuscript and flagged
# PASS/FAIL at the reported rounding precision.
#
# Input : ../input/analytic_sample.csv  (output of 1_preprocess.ipynb)
# Output: ../output/table_s4_interaction.csv
#         ../output/table_s5_wave_stratified.csv
#         ../output/table_s6_missing_data.csv
#         ../output/table_robustness.csv
#         ../output/verification_report.txt
# ══════════════════════════════════════════════════════════════
import os, sys
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import warnings
warnings.filterwarnings('ignore')

RNG_SEED = 20260703
np.random.seed(RNG_SEED)

HERE = os.path.dirname(os.path.abspath(__file__))  # repo/notebooks
INP = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, '..', 'output', 'pre_output', 'analytic_sample.csv')
OUT = os.path.join(HERE, '..', 'output', 'analysis_output', 'supplementary')
os.makedirs(OUT, exist_ok=True)

report = []
def log(msg=''):
    print(msg)
    report.append(str(msg))

checks = []
def check(name, got, expect, tol=0.005):
    """Compare a reproduced value against the manuscript value."""
    try:
        ok = abs(float(got) - float(expect)) <= tol
    except (TypeError, ValueError):
        ok = str(got) == str(expect)
    checks.append((name, got, expect, ok))
    log(f"  [{'PASS' if ok else 'FAIL'}] {name}: reproduced={got}  manuscript={expect}")
    return ok

# ── Load ──────────────────────────────────────────────────────
df = pd.read_csv(INP)
log(f'Loaded analytic sample: N={len(df):,}')
check('Descriptive sample N', len(df), 119912, tol=0)

# Regression-eligible sample (identical to 2_analysis.ipynb)
dfa = df.dropna(subset=['autonomy', 'support', 'lo_auto', 'lo_sup',
                        'edu_hi', 'poor_wlb']).copy()
check('Regression sample N', len(dfa), 83288, tol=0)

covars = 'age_c + age_c2 + female + edu_hi + long_hrs'
erg_covars = 'erg_posture_hi + erg_heavy_hi + erg_stand_hi + erg_repeat_hi'
full_controls = f'{covars} + {erg_covars} + wave_c + C(emp_type) + C(industry)'
POIS = dict(family=sm.families.Poisson(link=sm.families.links.Log()))

def fit(formula, data, weighted=True, cov_type='HC1', groups=None):
    kw = dict(POIS)
    if weighted:
        kw['freq_weights'] = data['swt']
    m = smf.glm(formula, data=data, **kw)
    if cov_type == 'cluster':
        return m.fit(cov_type='cluster', cov_kwds={'groups': groups})
    return m.fit(cov_type=cov_type)

def pr_ci(mod, var):
    pr = float(np.exp(mod.params[var]))
    lo, hi = np.exp(mod.conf_int().loc[var])
    return pr, float(lo), float(hi)

# ── 0. Primary model (anchor: must equal Table 2) ─────────────
log('\n════ 0. Primary Model A, any MSD (anchor vs Table 2) ════')
f_primary = f'msd_any ~ psy_demand + autonomy + support + {full_controls}'
m0 = fit(f_primary, dfa)
pr_a, lo_a, hi_a = pr_ci(m0, 'autonomy')
check('Primary autonomy PR', round(pr_a, 2), 0.84, tol=0.001)
check('Primary autonomy CI low', round(lo_a, 2), 0.83, tol=0.001)
check('Primary autonomy CI high', round(hi_a, 2), 0.86, tol=0.001)
# Demand is reported per unit toward LOWER demand (direction −1 in
# 2_analysis.ipynb): PR = exp(−β). exp(+β) is Table S2 (1.02).
pr_d = np.exp(-m0.params['psy_demand'])
check('Primary demand PR (reverse-coded)', round(pr_d, 2), 0.98, tol=0.001)
check('S2 demand PR (original orientation)', round(np.exp(m0.params['psy_demand']), 2), 1.02, tol=0.001)
pr_s = np.exp(m0.params['support'])
check('Primary support PR', round(pr_s, 2), 1.01, tol=0.001)

# ── 1. Table S4: interaction (multiplicative + RERI) ──────────
log('\n════ 1. Table S4 — autonomy × ergonomic interaction ════')
dfa['erg_any_hi'] = ((dfa['erg_posture_hi'] == 1) | (dfa['erg_heavy_hi'] == 1) |
                     (dfa['erg_stand_hi'] == 1) | (dfa['erg_repeat_hi'] == 1)).astype(float)

f_int = (f'msd_any ~ autonomy * erg_any_hi + psy_demand + support + '
         f'{covars} + wave_c + C(emp_type) + C(industry)')
m_int = fit(f_int, dfa)
mult, mult_lo, mult_hi = pr_ci(m_int, 'autonomy:erg_any_hi')
check('S4 multiplicative interaction', round(mult, 3), 1.169, tol=0.001)
check('S4 multiplicative CI low', round(mult_lo, 3), 1.114, tol=0.001)
check('S4 multiplicative CI high', round(mult_hi, 3), 1.226, tol=0.001)

# Quadrant model → RERI
dfa['lo_auto_binary'] = (dfa['lo_auto'] == 1).astype(float)
dfa['q_hi_auto_hi_erg'] = ((dfa['lo_auto_binary'] == 0) & (dfa['erg_any_hi'] == 1)).astype(float)
dfa['q_lo_auto_lo_erg'] = ((dfa['lo_auto_binary'] == 1) & (dfa['erg_any_hi'] == 0)).astype(float)
dfa['q_lo_auto_hi_erg'] = ((dfa['lo_auto_binary'] == 1) & (dfa['erg_any_hi'] == 1)).astype(float)
f_quad = (f'msd_any ~ q_hi_auto_hi_erg + q_lo_auto_lo_erg + q_lo_auto_hi_erg + '
          f'psy_demand + support + {covars} + wave_c + C(emp_type) + C(industry)')
m_quad = fit(f_quad, dfa)

qvars = ['q_hi_auto_hi_erg', 'q_lo_auto_lo_erg', 'q_lo_auto_hi_erg']
b = m_quad.params[qvars].values
V = m_quad.cov_params().loc[qvars, qvars].values
pr10, pr01, pr11 = np.exp(b)          # (hi-auto/hi-erg), (lo-auto/lo-erg), (lo-auto/hi-erg)
reri = pr11 - pr10 - pr01 + 1
grad = np.array([-pr10, -pr01, pr11])
se_reri = float(np.sqrt(grad @ V @ grad))
reri_lo_d, reri_hi_d = reri - 1.96 * se_reri, reri + 1.96 * se_reri
check('S4 RERI point', round(reri, 3), 0.054, tol=0.001)
check('S4 RERI delta CI low', round(reri_lo_d, 3), 0.012, tol=0.001)
check('S4 RERI delta CI high', round(reri_hi_d, 3), 0.095, tol=0.001)

# Parametric bootstrap (20,000 draws from MVN of quadrant coefficients)
draws = np.random.multivariate_normal(b, V, size=20000)
e = np.exp(draws)
reri_bs = e[:, 2] - e[:, 0] - e[:, 1] + 1
bs_lo, bs_hi = np.percentile(reri_bs, [2.5, 97.5])
check('S4 RERI bootstrap CI low', round(float(bs_lo), 3), 0.011, tol=0.002)
check('S4 RERI bootstrap CI high', round(float(bs_hi), 3), 0.095, tol=0.002)

pd.DataFrame([
    {'Quantity': 'Multiplicative interaction (ratio of PRs)', 'Estimate': round(mult, 3),
     'CI_lo': round(mult_lo, 3), 'CI_hi': round(mult_hi, 3),
     'p': m_int.pvalues['autonomy:erg_any_hi']},
    {'Quantity': 'RERI (delta method)', 'Estimate': round(reri, 3),
     'CI_lo': round(reri_lo_d, 3), 'CI_hi': round(reri_hi_d, 3), 'p': ''},
    {'Quantity': 'RERI (parametric bootstrap 20k)', 'Estimate': round(reri, 3),
     'CI_lo': round(float(bs_lo), 3), 'CI_hi': round(float(bs_hi), 3), 'p': ''},
]).to_csv(os.path.join(OUT, 'table_s4_interaction.csv'), index=False)

# Quadrant prevalences with binomial CIs (manuscript Fig 4A text)
log('\n  Quadrant prevalences (unweighted, 95% binomial CI):')
quad_expect = {  # label: (prev, lo, hi, n)
    'HiAuto_HiErg': (51.9, 51.3, 52.5, 29806),
    'LoAuto_LoErg': (21.9, 21.1, 22.6, 11455),
    'HiAuto_LoErg': (30.0, 29.2, 30.9, 11050),
    'LoAuto_HiErg': (43.4, 42.8, 44.0, 30977),
}
quad_def = {
    'HiAuto_HiErg': (0, 1), 'LoAuto_LoErg': (1, 0),
    'HiAuto_LoErg': (0, 0), 'LoAuto_HiErg': (1, 1),
}
for label, (a, g) in quad_def.items():
    sub = dfa[(dfa['lo_auto_binary'] == a) & (dfa['erg_any_hi'] == g)]
    n = len(sub); p = sub['msd_any'].mean()
    se = np.sqrt(p * (1 - p) / n)
    exp_p, exp_lo, exp_hi, exp_n = quad_expect[label]
    check(f'Quadrant {label} n', n, exp_n, tol=0)
    check(f'Quadrant {label} prev %', round(p * 100, 1), exp_p, tol=0.05)
    check(f'Quadrant {label} CI low', round((p - 1.96 * se) * 100, 1), exp_lo, tol=0.1)
    check(f'Quadrant {label} CI high', round((p + 1.96 * se) * 100, 1), exp_hi, tol=0.1)

# ── 2. Table S5: wave-stratified + exposure×wave tests ────────
log('\n════ 2. Table S5 — wave-stratified autonomy PRs ════')
f_wave = (f'msd_any ~ psy_demand + autonomy + support + {covars} + '
          f'{erg_covars} + C(emp_type) + C(industry)')
s5_expect = {2: (2605, 0.94, 0.87, 1.02), 3: (15701, 0.92, 0.89, 0.96),
             4: (16417, 0.93, 0.90, 0.96), 5: (22137, 0.76, 0.73, 0.80),
             6: (14004, 0.80, 0.77, 0.83), 7: (12424, 0.80, 0.77, 0.83)}
s5_rows = []
for w in sorted(dfa['wave'].unique()):
    sub = dfa[dfa['wave'] == w]
    mw = fit(f_wave, sub)
    pr, lo, hi = pr_ci(mw, 'autonomy')
    n_exp, pr_exp, lo_exp, hi_exp = s5_expect[int(w)]
    check(f'S5 W{int(w)} n', len(sub), n_exp, tol=0)
    check(f'S5 W{int(w)} autonomy PR', round(pr, 2), pr_exp, tol=0.001)
    check(f'S5 W{int(w)} CI low', round(lo, 2), lo_exp, tol=0.001)
    check(f'S5 W{int(w)} CI high', round(hi, 2), hi_exp, tol=0.001)
    s5_rows.append({'wave': int(w), 'n': len(sub), 'PR': round(pr, 2),
                    'CI_lo': round(lo, 2), 'CI_hi': round(hi, 2)})
pd.DataFrame(s5_rows).to_csv(os.path.join(OUT, 'table_s5_wave_stratified.csv'), index=False)

# exposure × wave interaction: single-df Wald test on the
# exposure × wave_c (linear wave) product term, one exposure at a time
# — this is the specification that reproduces the manuscript p-values.
log('\n  Exposure × wave interaction tests (exposure × wave_c, single df):')
for expo, p_manu, p_hi in [('autonomy', 0.0001, True), ('psy_demand', 0.20, False),
                           ('support', 0.0002, False)]:
    f_x = (f'msd_any ~ psy_demand + autonomy + support + {expo}:wave_c + '
           f'{covars} + {erg_covars} + wave_c + C(emp_type) + C(industry)')
    mx = fit(f_x, dfa)
    pval = float(mx.pvalues[f'{expo}:wave_c'])
    if p_hi:
        check(f'{expo} × wave p < 0.0001', int(pval < 0.0001), 1, tol=0)
    else:
        check(f'{expo} × wave p', round(pval, 4 if p_manu < 0.01 else 2), p_manu,
              tol=0.0001 if p_manu < 0.01 else 0.005)

# ── 3. Table S6: missing-data sensitivity ─────────────────────
log('\n════ 3. Table S6 — support-omitted + multiple imputation ════')
dfb = df.dropna(subset=['autonomy', 'lo_auto', 'edu_hi', 'poor_wlb']).copy()
check('S6 retained-sample n', len(dfb), 118673, tol=0)

f_noSup = f'msd_any ~ psy_demand + autonomy + {full_controls}'
m_ns = fit(f_noSup, dfb)
pr, lo, hi = pr_ci(m_ns, 'autonomy')
check('S6 support-omitted autonomy PR', round(pr, 2), 0.85, tol=0.001)
check('S6 support-omitted CI low', round(lo, 2), 0.84, tol=0.001)
check('S6 support-omitted CI high', round(hi, 2), 0.86, tol=0.001)

# Multiple imputation of the support scale (m=10, Rubin's rules).
# Support is imputed from a linear model on all analytic covariates,
# with posterior draws of coefficients and residual variance
# (Bayesian linear regression imputation, seed fixed).
log('\n  Multiple imputation of support (m=10):')
imp_covs = ['psy_demand', 'autonomy', 'age_c', 'age_c2', 'female', 'edu_hi',
            'long_hrs', 'erg_posture_hi', 'erg_heavy_hi', 'erg_stand_hi',
            'erg_repeat_hi', 'wave_c', 'msd_any']
obs = dfb['support'].notna()
X_obs = sm.add_constant(dfb.loc[obs, imp_covs].astype(float))
y_obs = dfb.loc[obs, 'support'].astype(float)
ols = sm.OLS(y_obs, X_obs).fit()
X_mis = sm.add_constant(dfb.loc[~obs, imp_covs].astype(float))
X_mis = X_mis[X_obs.columns]
betas, cov_b = ols.params.values, ols.cov_params().values
sigma2, df_res = ols.mse_resid, ols.df_resid

M = 10
qs, us = [], []
for m in range(M):
    s2_draw = sigma2 * df_res / np.random.chisquare(df_res)
    b_draw = np.random.multivariate_normal(betas, cov_b * s2_draw / sigma2)
    y_imp = X_mis.values @ b_draw + np.random.normal(0, np.sqrt(s2_draw), len(X_mis))
    d_m = dfb.copy()
    d_m.loc[~obs, 'support'] = np.clip(y_imp, 1, 5)
    m_i = fit(f_primary, d_m)
    qs.append(float(m_i.params['autonomy']))
    us.append(float(m_i.bse['autonomy']) ** 2)
qbar = np.mean(qs); ubar = np.mean(us)
bvar = np.var(qs, ddof=1)
tvar = ubar + (1 + 1 / M) * bvar
se_mi = np.sqrt(tvar)
pr_mi = np.exp(qbar)
lo_mi, hi_mi = np.exp(qbar - 1.96 * se_mi), np.exp(qbar + 1.96 * se_mi)
check('S6 MI autonomy PR', round(pr_mi, 2), 0.85, tol=0.005)
check('S6 MI CI low', round(lo_mi, 2), 0.84, tol=0.005)
check('S6 MI CI high', round(hi_mi, 2), 0.86, tol=0.005)

pd.DataFrame([
    {'Analysis': 'Primary complete-case', 'n': len(dfa), 'PR': round(pr_a, 2),
     'CI_lo': round(lo_a, 2), 'CI_hi': round(hi_a, 2)},
    {'Analysis': 'Support-omitted', 'n': len(dfb), 'PR': round(pr, 2),
     'CI_lo': round(lo, 2), 'CI_hi': round(hi, 2)},
    {'Analysis': 'Multiple imputation (m=10, Rubin)', 'n': len(dfb),
     'PR': round(pr_mi, 2), 'CI_lo': round(lo_mi, 2), 'CI_hi': round(hi_mi, 2)},
]).to_csv(os.path.join(OUT, 'table_s6_missing_data.csv'), index=False)

# ── 4. Robustness: total vs direct, age strata, cluster, E-value ──
log('\n════ 4. Robustness analyses ════')
rob_rows = []

# Total effect (ergonomic covariates omitted)
f_tot = f'msd_any ~ psy_demand + autonomy + support + {covars} + wave_c + C(emp_type) + C(industry)'
m_tot = fit(f_tot, dfa)
prt, lot, hit = pr_ci(m_tot, 'autonomy')
check('Total effect autonomy PR', round(prt, 2), 0.83, tol=0.001)
check('Total effect CI low', round(lot, 2), 0.82, tol=0.001)
check('Total effect CI high', round(hit, 2), 0.85, tol=0.001)
rob_rows.append({'Analysis': 'Total effect (no ergonomic covariates)', 'n': len(dfa),
                 'PR': round(prt, 2), 'CI_lo': round(lot, 2), 'CI_hi': round(hit, 2)})

# Age-stratified
log('\n  Age-stratified autonomy PRs:')
age_bands = [('15-39', 15, 39, 0.77, 0.75, 0.80), ('40-54', 40, 54, None, None, None),
             ('55+', 55, 200, 0.93, 0.90, 0.95)]
# The age terms (age_c, age_c2) are retained within each stratum —
# this is the specification that reproduces the manuscript estimates.
f_age = f'msd_any ~ psy_demand + autonomy + support + {full_controls}'
for label, a0, a1, e_pr, e_lo, e_hi in age_bands:
    sub = dfa[(dfa['age_raw'] >= a0) & (dfa['age_raw'] <= a1)]
    ma = fit(f_age, sub)
    pr, lo, hi = pr_ci(ma, 'autonomy')
    if e_pr is not None:
        check(f'Age {label} autonomy PR', round(pr, 2), e_pr, tol=0.001)
        check(f'Age {label} CI low', round(lo, 2), e_lo, tol=0.001)
        check(f'Age {label} CI high', round(hi, 2), e_hi, tol=0.001)
    else:
        log(f'  Age {label}: PR={pr:.2f} ({lo:.2f}-{hi:.2f}) n={len(sub):,}')
    rob_rows.append({'Analysis': f'Age-stratified {label}', 'n': len(sub),
                     'PR': round(pr, 2), 'CI_lo': round(lo, 2), 'CI_hi': round(hi, 2)})

# Cluster-by-wave variance
m_cl = fit(f_primary, dfa, cov_type='cluster', groups=dfa['wave'])
prc, loc_, hic = pr_ci(m_cl, 'autonomy')
check('Cluster-by-wave autonomy PR', round(prc, 2), 0.84, tol=0.001)
check('Cluster-by-wave CI low', round(loc_, 2), 0.78, tol=0.001)
check('Cluster-by-wave CI high', round(hic, 2), 0.91, tol=0.001)
rob_rows.append({'Analysis': 'Variance clustered by wave', 'n': len(dfa),
                 'PR': round(prc, 2), 'CI_lo': round(loc_, 2), 'CI_hi': round(hic, 2)})

# E-value for PR 0.84 (protective → invert)
rr = 1 / 0.84
evalue = rr + np.sqrt(rr * (rr - 1))
check('E-value for autonomy PR 0.84', round(evalue, 2), 1.67, tol=0.005)
rob_rows.append({'Analysis': 'E-value (autonomy PR 0.84)', 'n': '',
                 'PR': round(evalue, 2), 'CI_lo': '', 'CI_hi': ''})

pd.DataFrame(rob_rows).to_csv(os.path.join(OUT, 'table_robustness.csv'), index=False)

# ── 5. Model-specification note (manuscript text vs code) ─────
log('\n════ 5. Specification check: manuscript text vs actual code ════')
n_edu = dfa['edu'].nunique(); n_ind = dfa['industry'].nunique()
n_emp = dfa['emp_type'].nunique()
log(f'  Distinct education levels in data: {n_edu} (model uses BINARY edu_hi)')
log(f'  Distinct industries: {n_ind}; employment types: {n_emp}')
f_alt = (f'msd_any ~ psy_demand + autonomy + support + age_c + age_c2 + female + '
         f'long_hrs + {erg_covars} + C(edu) + C(wave) + C(emp_type) + C(industry)')
m_alt = fit(f_alt, dfa)
pra, loa, hia = pr_ci(m_alt, 'autonomy')
log(f'  Alternative spec (5-cat education, categorical wave): '
    f'autonomy PR={pra:.3f} ({loa:.3f}-{hia:.3f})')
log(f'  Actual spec   (binary edu_hi, continuous wave_c):    '
    f'autonomy PR={pr_a:.3f} ({lo_a:.3f}-{hi_a:.3f})')

# ── 6. Descriptive anchors (Table 1 / trend endpoints) ────────
log('\n════ 6. Descriptive anchors ════')
t1 = df.groupby('wave').agg(n=('wave', 'size'))
for w, n_exp in [(2, 3682), (3, 21308), (4, 24146), (5, 30752), (6, 21164), (7, 18860)]:
    check(f'Table1 W{w} N', int(t1.loc[w, 'n']), n_exp, tol=0)

def wmean(sub, col):
    v = sub[col].dropna()
    return np.average(v, weights=sub.loc[v.index, 'swt']) * 100

for col, w, expect in [('lo_auto', 2, 34.3), ('lo_auto', 7, 64.4),
                       ('msd_any', 2, 49.1), ('msd_any', 5, 31.4),
                       ('psy_demand_hi', 2, 42.9), ('psy_demand_hi', 7, 26.3),
                       ('lo_sup', 2, 40.3), ('lo_sup', 7, 32.4)]:
    got = round(wmean(df[df['wave'] == w], col), 1)
    check(f'Weighted {col} W{w} %', got, expect, tol=0.05)

# ── Summary ───────────────────────────────────────────────────
n_pass = sum(1 for c in checks if c[3]); n_fail = len(checks) - n_pass
log(f'\n══════════ VERIFICATION SUMMARY: {n_pass} PASS / {n_fail} FAIL ══════════')
if n_fail:
    log('Failed checks:')
    for name, got, expect, ok in checks:
        if not ok:
            log(f'  FAIL {name}: reproduced={got} manuscript={expect}')

with open(os.path.join(OUT, 'verification_report.txt'), 'w') as fh:
    fh.write('\n'.join(report))
print('\nSaved:', os.path.join(OUT, 'verification_report.txt'))
sys.exit(1 if n_fail else 0)
